services:
  db:
    container_name: "db_test"
    image: postgres:15.3-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge